name: Release

on:
  workflow_run:
    workflows: ["wizo - CI"]
    types: [completed]
    branches: [staging, stable]

jobs:
  release:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    outputs:
      release_created: ${{ steps.semantic.outputs.new_release_published }}
      tag_name: ${{ steps.semantic.outputs.new_release_version }}

    permissions:
      contents: write
      pull-requests: write
      id-token: write
      issues: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'

      - name: Pre-install Semantic Release Plugins
        run: |
          npm init -y
          npm install semantic-release @semantic-release/git @semantic-release/cargo conventional-changelog-conventionalcommits --no-audit

      - name: Run Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        with:
          branch: ${{ github.event.workflow_run.head_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-deploy:
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    runs-on: ${{ matrix.platform.os || 'ubuntu-latest' }}
    strategy:
      matrix:
        platform:
          - name: linux-x86_64
            target: x86_64-unknown-linux-musl
            use-cross: true
            output: wizo
            asset_suffix: linux-x86_64
            
          - name: linux-aarch64
            target: aarch64-unknown-linux-musl
            use-cross: true
            output: wizo
            asset_suffix: linux-aarch64
            
          - name: windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
            output: wizo.exe
            asset_suffix: windows-x86_64.exe

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ needs.release.outputs.tag_name }}

    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.platform.target }}

    - name: Cache Cargo Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.platform.target }}
      
    - name: Install Cross
      if: matrix.platform.use-cross
      run: cargo install cross

    - name: Build - ${{ matrix.platform.name }}
      run: |
        if [ "${{ matrix.platform.use-cross }}" = "true" ]; then
          cross build -r --target ${{ matrix.platform.target }}
        else
          cargo build -r --target ${{ matrix.platform.target }}
        fi
        cp ./target/${{ matrix.platform.target }}/release/${{ matrix.platform.output }} ./target/${{ matrix.platform.target }}/release/${{ needs.release.outputs.tag_name }}-${{ matrix.platform.asset_suffix }}
      shell: bash

    - name: Push Build Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: wizo-artifact-${{ matrix.platform.name }}
        path: target/${{ matrix.platform.target }}/release/${{ needs.release.outputs.tag_name }}-${{ matrix.platform.asset_suffix }}
        retention-days: 5

  github-release:
    needs: [release, build-deploy]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist
          pattern: wizo-artifact-*
          merge-multiple: true

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: ./dist/*
          tag_name: ${{ needs.release.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-crates-io:
    needs: [release, github-release]
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ needs.release.outputs.tag_name }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish